// src/frontend/app/pages/signup.vue
<template>
  <main class="container">
    <h1>📄 PDF Analyzer</h1>
    <div class="card">
      <h2>Sign Up</h2>
      <input v-model="email" type="email" placeholder="Email" />
      <input v-model="password" type="password" placeholder="Password (min 8 chars, upper+lower+number)" />
      <input v-model="confirmPassword" type="password" placeholder="Confirm Password" />
      <button @click="handleSignup">Sign Up</button>
      <div v-if="error" class="error">{{ error }}</div>
      <p class="link-text">Already have an account? <NuxtLink to="/login">Login</NuxtLink></p>
    </div>
  </main>
</template>

<script setup lang="ts">
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const error = ref('')
const { signUp } = useAuth()

async function handleSignup() {
  try {
    error.value = ''
    if (password.value !== confirmPassword.value) {
      error.value = 'Passwords do not match'
      return
    }
    await signUp(email.value, password.value)
    localStorage.setItem('pendingEmail', email.value)
    navigateTo('/confirm')
  } catch (e: any) {
    error.value = e.message
  }
}
</script>

// src/frontend/src/app/signup/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { signUp } from '@/auth';

// Signup Page - Simple registration form
export default function SignupPage() {
  const router = useRouter();
  
  // Form fields
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');

  // Handle signup button click
  async function handleSignup() {
    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    // Call the auth API
    await signUp(email, password);
    
    // Save email for confirmation page
    localStorage.setItem('pendingEmail', email);
    
    // Go to confirmation page
    router.push('/confirm');
  }

  return (
    <main className="container">
      <h1>📄 PDF Analyzer</h1>
      
      <div className="card">
        <h2>Sign Up</h2>
        
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        
        <input
          type="password"
          placeholder="Password (min 8 chars, upper+lower+number)"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />

        <input
          type="password"
          placeholder="Confirm Password"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
        />
        
        <button onClick={handleSignup}>Sign Up</button>
        
        {error && <div className="error">{error}</div>}
        
        <p className="link-text">
          Already have an account? <a href="/login">Login</a>
        </p>
      </div>
    </main>
  );
}
